# Generated by Django 5.0.3 on 2024-04-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linkfeed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_rss_feed_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
