# Generated by Django 5.0.3 on 2024-04-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Linkfeed", "0002_comment_parent_comment_post_repost_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="display_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
