# Generated by Django 5.0.3 on 2024-04-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linkfeed', '0003_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.URLField(blank=True, null=True),
        ),
    ]
