# Generated by Django 5.0.3 on 2024-04-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linkfeed', '0004_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_imported_rss_feed_post',
            field=models.BooleanField(default=False),
        ),
    ]
