# Generated by Django 5.0.3 on 2024-04-06 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linkfeed', '0005_post_is_imported_rss_feed_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_imported_rss_feed_post',
        ),
        migrations.AddField(
            model_name='post',
            name='imported_rss_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='Linkfeed.importedrssfeed'),
        ),
    ]
