# Generated by Django 5.0.3 on 2024-04-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Linkfeed', '0006_remove_post_is_imported_rss_feed_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_imported_rss_feed_post',
            field=models.BooleanField(default=False),
        ),
    ]
